# Generated by Django 4.1.2 on 2022-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[("user_id", models.AutoField(primary_key=True, serialize=False)),],
        ),
    ]
