# Generated by Django 4.1.2 on 2022-11-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="MyName", max_length=100),
            preserve_default=False,
        ),
    ]
