# Generated by Django 4.1.2 on 2022-10-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("ride_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver",
                        to="users.user",
                    ),
                ),
                (
                    "passengers",
                    models.ManyToManyField(
                        blank=True, through="rides.Participation", to="users.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participation",
            name="ride",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="rides.ride"
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passenger",
                to="users.user",
            ),
        ),
    ]
