# Generated by Django 4.1.2 on 2022-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="city_from",
            field=models.CharField(default="", max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="city_to",
            field=models.CharField(default="", max_length=110),
            preserve_default=False,
        ),
    ]
