# Generated by Django 4.1.2 on 2022-11-11 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_add_city_from_and_to_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
