# Generated by Django 4.1.2 on 2022-10-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("stars", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("was_rated_driver", models.BooleanField()),
                (
                    "rated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rated",
                        to="users.user",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reviewer",
                        to="users.user",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="rides.ride"
                    ),
                ),
            ],
        ),
    ]
