# Generated by Django 4.1.2 on 2022-11-01 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_on",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
